GET  http://localhost:5000


###
POST http://localhost:5000/signUp
Content-Type: application/json

{
    
    "password": "Password12@"
  
}

###

POST http://localhost:5000/signIn
Content-Type: application/json

{
    "email": "knaan@uia.no",
    "password": "Password12@"
}
 