GET  http://localhost:5000


###
POST http://localhost:5000/signUp
Content-Type: application/json

{



    "email": "knaan@uia.no",


    "password": "Password12@"
  
}


###

POST http://localhost:5000/image
Content-Type: application/json

{
    "path": "gs://cooktogo-cec09.appspot.com/image17.jpg"
   
}




### 
POST http://localhost:5000/singOut
Content-Type: application/json

{
    "email": "knaan@uia.no",
    "password": "Password12@"
}

### 
POST http://localhost:5000/forgetPassword
Content-Type: application/json

{
    "email": "mohamedzekaria@gmail.com"
    
}


